image: registry.atosresearch.eu:18467/cython:3.8-slim-cicd

variables:
  PACKAGE: template
  JOB_WITH_COVERAGE: test_functional
  GITLAB_URL: https://scm.atosresearch.eu

stages:
  - build
  - adapt
  - tests
  - release

build_wheel:
  stage: build
  only:
    - develop
    - master
    - merge_requests
  script:
    - rm -f .env
    - touch .env
    - echo "USER_PASSWORD="$API_TOKEN >> .env  # To install sns.manowrappers from develop branch
    - pypi_wrapper build --cython --clean-dist
  artifacts:
    paths:
      - dist/*.whl
      - .env

adapt_wheel:
  image: quay.io/pypa/manylinux2014_x86_64 # https://github.com/pypa/auditwheel
  stage: adapt
  dependencies:
    - build_wheel
  only:
    - develop
    - master
    - merge_requests
  script:
    - auditwheel show dist/*
    - auditwheel repair dist/*
    - rm -f dist/*
    - cp wheelhouse/* dist/
  artifacts:
    paths:
      - dist/*.whl
      - .env

test_functional:
  stage: tests
  only:
    - develop
    - master
    - merge_requests
  dependencies:
    - adapt_wheel
  script:
    - echo "Installing template in develop mode for coverage purpose"
    - rm -f .env
    - touch .env
    - echo "USER_PASSWORD="$API_TOKEN >> .env  # To install sns.manowrappers from develop branch
    - apt-get update
    - apt-get install git -y --no-install-recommends  # TODO: Remove when sns-manowrappers 1.1.0 is released
    - pytest tests --cov=${PACKAGE} --cov-report html --cov-report term-missing
    - cp -r htmlcov reports
  coverage: '/TOTAL.+?(\d+%)/'

  artifacts:
    paths:
      - reports/htmlcov

qa:
  stage: tests
  dependencies:
    - adapt_wheel
  only:
    - develop
    - master
    - merge_requests
  script:
    - apt-get update
    - apt-get install git -y --no-install-recommends  # TODO: Remove when sns-manowrappers 1.1.0 is released
    # pylint will fail return non-zero even if only warnings are found
    - pylint $PACKAGE tests --exit-zero --reports y >> qa_report.txt
    - cat qa_report.txt
    - pylint_wrapper --pylint-report-path qa_report.txt raise-for-code
    - mkdir reports/
    - cp qa_report.txt reports/
  artifacts:
    paths:
      - reports/qa_report.txt

make_badges: # Only update when merged to main branches
  stage: release
  dependencies:
    - qa
    - adapt_wheel
  only:
    - master
    - develop
  script:
    - apt-get update
    - apt-get install git -y --no-install-recommends  # TODO: Remove when sns-manowrappers 1.1.0 is released
    - QA=$(pylint_wrapper --pylint-report-path reports/qa_report.txt get-qa-value | tail -1)
    - echo ${QA}
    - VERSION=$(python -c "import pkg_resources; print(pkg_resources.get_distribution('$PACKAGE').version)")
    - echo ${VERSION}
    - gitlab_wrapper update-badge --url $GITLAB_URL --api-token ${API_TOKEN}
      --project-id ${CI_PROJECT_ID} --pipeline-id ${CI_PIPELINE_ID} --version ${VERSION} --version-badge-name Version
      --test-job-name $JOB_WITH_COVERAGE --coverage-badge-name Coverage --qa-value ${QA} --pylint-badge-name Pylint
  artifacts:
    paths:
      - Coverage.svg
      - Version.svg
      - Pylint.svg